version: '3.9'

volumes:
  postgres_data_pwa:

services:
  romissia:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: pwa
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.django
      - ./.env.postgres
    depends_on:
      - postgres_pwa

  postgres_pwa:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_pwa
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - postgres_data_pwa:/var/lib/postgresql/data/
    env_file:
      - ./.env.postgres


